// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	vaulttypes "github.com/ajugalushkin/goph-keeper/client/internal/vaulttypes"
	mock "github.com/stretchr/testify/mock"
)

// Vault is an autogenerated mock type for the Vault type
type Vault struct {
	mock.Mock
}

// String provides a mock function with given fields:
func (_m *Vault) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Type provides a mock function with given fields:
func (_m *Vault) Type() vaulttypes.VaultType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 vaulttypes.VaultType
	if rf, ok := ret.Get(0).(func() vaulttypes.VaultType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(vaulttypes.VaultType)
	}

	return r0
}

// NewVault creates a new instance of Vault. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVault(t interface {
	mock.TestingT
	Cleanup(func())
}) *Vault {
	mock := &Vault{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
