issues:
  exclude-dirs:
    - gen
    - mocks
    - client/internal/vaulttypes/mocks
    - client/internal/app/mocks
    - server/internal/services/mocks
    - server/internal/app/grpc/mocks
    - server/internal/handlers/grpc/auth/v1/mocks
    - server/internal/handlers/grpc/keeper/v1/mocks
    - server/internal/storage/mocks
  exclude:
    - "server/internal/handlers/grpc/keeper/v1/mocks/CreateItemStreamServer.go"