version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - goph-keeper-network
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?Please configure MINIO_ROOT_USER in the .env file}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?Please configure MINIO_ROOT_PASSWORD in the .env file}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS:?Please configure MINIO_DEFAULT_BUCKETS in the .env file}
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}