services:
  goph-keeper:
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    build:
      context: ../
      dockerfile: ../server/Dockerfile
    image: goph-keeper:v1.0
    container_name: goph-keeper
    hostname: goph-keeper
    ports:
      - 8080:8080
      - 40000:40000
    environment:
      CONFIG: ${CONFIG:?Please configure CONFIG in the .env file}
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec /server
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - goph-keeper-network