services:
  goph-keeper:
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - ci.env
      - .env
    build:
      context: ../
      dockerfile: ./server/cmd/Dockerfile
    image: goph-keeper:latest
    container_name: goph-keeper
    hostname: goph-keeper
    ports:
      - 8080:8080
      - 40000:40000
    environment:
      SERVER_CONFIG: ${SERVER_CONFIG:?Please configure SERVER_CONFIG in the .env file}
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec /server
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - goph-keeper-network