// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/ajugalushkin/goph-keeper/gen/auth/v1"
)

// AuthServiceV1Client is an autogenerated mock type for the AuthServiceV1Client type
type AuthServiceV1Client struct {
	mock.Mock
}

// LoginV1 provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceV1Client) LoginV1(ctx context.Context, in *v1.LoginRequestV1, opts ...grpc.CallOption) (*v1.LoginResponseV1, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for LoginV1")
	}

	var r0 *v1.LoginResponseV1
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.LoginRequestV1, ...grpc.CallOption) (*v1.LoginResponseV1, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.LoginRequestV1, ...grpc.CallOption) *v1.LoginResponseV1); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.LoginResponseV1)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.LoginRequestV1, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterV1 provides a mock function with given fields: ctx, in, opts
func (_m *AuthServiceV1Client) RegisterV1(ctx context.Context, in *v1.RegisterRequestV1, opts ...grpc.CallOption) (*v1.RegisterResponseV1, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterV1")
	}

	var r0 *v1.RegisterResponseV1
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequestV1, ...grpc.CallOption) (*v1.RegisterResponseV1, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.RegisterRequestV1, ...grpc.CallOption) *v1.RegisterResponseV1); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RegisterResponseV1)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.RegisterRequestV1, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthServiceV1Client creates a new instance of AuthServiceV1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceV1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceV1Client {
	mock := &AuthServiceV1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
