// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeKeeperServiceV1Server is an autogenerated mock type for the UnsafeKeeperServiceV1Server type
type UnsafeKeeperServiceV1Server struct {
	mock.Mock
}

// mustEmbedUnimplementedKeeperServiceV1Server provides a mock function with given fields:
func (_m *UnsafeKeeperServiceV1Server) mustEmbedUnimplementedKeeperServiceV1Server() {
	_m.Called()
}

// NewUnsafeKeeperServiceV1Server creates a new instance of UnsafeKeeperServiceV1Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeKeeperServiceV1Server(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeKeeperServiceV1Server {
	mock := &UnsafeKeeperServiceV1Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
