// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeAuthServiceV1Server is an autogenerated mock type for the UnsafeAuthServiceV1Server type
type UnsafeAuthServiceV1Server struct {
	mock.Mock
}

// mustEmbedUnimplementedAuthServiceV1Server provides a mock function with given fields:
func (_m *UnsafeAuthServiceV1Server) mustEmbedUnimplementedAuthServiceV1Server() {
	_m.Called()
}

// NewUnsafeAuthServiceV1Server creates a new instance of UnsafeAuthServiceV1Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeAuthServiceV1Server(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeAuthServiceV1Server {
	mock := &UnsafeAuthServiceV1Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
