name: Build Artifacts

on: [ push, pull_request ]

jobs:
  upload:
    name: Generate Build Artifacts

    strategy:
      matrix:
        GOOS: [ darwin, linux, windows ]
        GOARCH: [ arm64, 386 ]

    runs-on: ${{ matrix.GOOS }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build
        run: GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -C client -o bin/client-cli-${{ matrix.os }}-${{ matrix.GOARCH }} main.go
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: client-cli-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: bin