name: Build Artifacts

on: [ push, pull_request ]

jobs:
  upload:
    name: Generate Build Artifacts

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build
        run: |
          GOOS=darwin GOARCH=amd64 go build -C client -o bin-macos-latest/client-cli-darwin-amd64 main.go
          GOOS=linux GOARCH=amd64 go build -C client -o bin-ubuntu-latest/client-cli-linux-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -C client -o bin-windows-latest/client-cli-windows-amd64 main.go
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: assets-for-download-${{ matrix.os }}
          path: bin-${{ matrix.os }}