name: Build Artifacts

on: [ push, pull_request ]

jobs:
  upload:
    name: Generate Build Artifacts

    strategy:
      matrix:
#        os: [ macos-latest, ubuntu-latest, windows-latest ]
        version: [ a, b, c ]
        os: [ darwin, linux, windows ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Build
        run: GOOS=${{ matrix.os }} GOARCH=arm64 go build -C client -o bin/client-cli-${{ matrix.os }}-${{ matrix.version }} main.go
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: client-cli-${{ matrix.os }}-${{ matrix.version }}
          path: bin