name: Build Go Binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: linux
    steps:
      - name: Get Release Info
        run: |
          echo RELEASE_TAG=${GITHUB_REF/refs\/tags\//} >> $GITHUB_ENV
          echo RELEASE_TIME=$(date -u +%Y/%m/%d-%H:%M:%S) >> $GITHUB_ENV
          echo RELEASE_COMMIT=`echo ${GITHUB_SHA} | cut -c1-8` >> $GITHUB_ENV
          echo REPOSITORY_NAME=${GITHUB_REPOSITORY#*/} >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: |
            -X "github.com/ajugalushkin/goph-keeper/common/version.BuildVersion=${{env.RELEASE_TAG}}"
            -X "github.com/ajugalushkin/goph-keeper/icommon/version.BuildDate=${{env.RELEASE_TIME}}"
            -X "github.com/ajugalushkin/goph-keeper/common/version.BuildCommit=${{env.RELEASE_COMMIT}}"
          project_path: client
          asset_name: "${{ env.REPOSITORY_NAME }}-${{ env.RELEASE_TAG }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          md5sum: false